services:
  api01: &app
    image: thiagorigonatti/rinha-2025:0.0.9
    environment:
      - PTHREADS=2
      - SOCK_PATH=/dev/shm/server1.sock
    networks:
      - api
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "30MB"
    volumes:
      - /dev/shm:/dev/shm

  api02:
    <<: *app
    environment:
      - PTHREADS=2
      - SOCK_PATH=/dev/shm/server2.sock
  haproxy:
    image: haproxy:3.3-dev5-alpine3.22
    volumes:
      - /dev/shm:/dev/shm
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200MB"
    networks:
      - api
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
